### ISSUE TITLE
name conflict

### ISSUE THREAD

**Issue by mariorossi77** [djt3/minitube#2]
i'd like to package minitube in the AUR but minitube already exists
https://flavio.tordini.org/minitube
https://archlinux.org/packages/community/x86_64/minitube/

would you kindly suggest an alternative name?

**Comment by djt3** [comment]
How about "litetube"? Feel free to suggest any ideas you have

**Comment by mariorossi77** [comment]
minipipe
litetube
microtube
tinytube

all of these are "available"

**Comment by djt3** [comment]
tinytube sounds good to me

**Comment by mariorossi77** [comment]
> tinytube sounds good to me
